[project]
name = "ai-orchestrator"
version = "8.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "commitizen>=4.13.10",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "release/orchestrator/$version"
version_scheme = "semver2"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = false
breaking_change_exclamation_in_title = true
template = "CHANGELOG.md.j2"
