name: Create Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run - Create Changelog to stdout'
        required: false
        type: boolean
      package:
        description: 'Which slug to release'
        type: choice
        options:
          - orchestrator
          - evals
        default: orchestrator
      increment:
        description: 'Choose version bump strategy: AUTO (based on commits), or force MAJOR, MINOR or PATCH increment.'
        type: choice
        options:
          - AUTO
          - MAJOR
          - MINOR
          - PATCH
        default: AUTO
  #push:
  #  branches:
  #    - 'release/*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

env:
  GIT_AUTHOR_NAME: "tmiklu"
  GIT_COMMITTER_NAME: "tmiklu"
  EMAIL: "tomas.miklusicak@cloudops.sk"

jobs:
  generate-release-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Validate commits from default branch to HEAD
        run: |
          cd "apps/${{ inputs.package }}"
          uv run cz check --rev-range 60c33eb3a009eb676395ddc45a0dd04c1a621348 \
            --allowed-prefixes 'Merge' 'Revert' 'bump'
        
      - name: Dry run, output changelog to stdout
        run: |
          INC=${{ inputs.increment }}
          DRY_RUN="${{ inputs.dry-run == true }}"
          cd "apps/${{ inputs.package }}"
          if [[ "$DRY_RUN" == "true" ]] ; then
            echo dry-run
            uv run cz bump --yes --dry-run
          fi
          if [[ "$INC" == "AUTO" ]]; then
            echo AUTO
            uv run cz bump --yes --dry-run
          elif [[ -z "$INC" ]]; then
            uv run cz bump --yes --dry-run
          else
            uv run cz bump --increment "$INC" --dry-run
          fi

  release:
    if: ${{ inputs.dry-run == false }}
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    runs-on: ubuntu-latest
    environment: release
    needs: generate-release-log
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Bump and Create Changelog
        run: |
          INC=${{ inputs.increment }}
          cd "apps/${{ inputs.package }}"
          if [[ "$INC" == "AUTO" ]]; then
            uv run cz bump --yes
          elif [[ -z "$INC" ]]; then
            uv run cz bump --yes
          else
            uv run cz bump --increment "$INC"
          fi

      - name: Push commits with tags
        run: | 
          git push && git push --tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cd "apps/${{ inputs.package }}"
          TAG=$(uv run cz version --project)
          grep "^## $TAG" CHANGELOG.md > release.md                                    
          awk "/## $TAG/{flag=1;next}/## [0-9]+/{flag=0}flag" CHANGELOG.md >> release.md
          gh release create "$TAG" \
            --title "$TAG" \
            --notes-file release.md
