name: Create Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: >
          Run in dry-run mode and print the generated changelog to stdout.
        required: false
        default: true
        type: boolean
      package:
        description: >
          Select the package to release.
        type: choice
        options:
          - orchestrator
          - evals
        default: orchestrator
      increment:
        description: >
          Version bump strategy:
          AUTO detects the increment from commits,
          or explicitly force MAJOR, MINOR, or PATCH.
        type: choice
        options:
          - AUTO
          - MAJOR
          - MINOR
          - PATCH
        default: AUTO
      validate-commit:
        description: >
          Validate the latest N commit messages.
          Use 0 to skip validation.
        type: number
        default: 0

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

env:
  GIT_AUTHOR_NAME: "projectx-ci-bot[bot]"
  GIT_COMMITTER_NAME: "projectx-ci-bot[bot]"
  EMAIL: "projectx-ci-bot[bot]@users.noreply.github.com"

jobs:    
  validate-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "apps/${{ inputs.package }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: "Validate commits to HEAD"
        if: ${{ inputs.validate-commit != 0 }}
        run: |
          NUMBER_OF_COMMITS="HEAD~${{ inputs.validate-commit }}.."
          uv run cz check --rev-range $NUMBER_OF_COMMITS

      - name: Output changelog to stdout
        if: "${{ inputs.dry-run == true }}"
        run: |
          CHANGE_LOG_DRY_RUN="changelog-dry-run.md"
          if [[ "$INC" == "AUTO" || -z "$INC" ]]; then
            echo "GET_NEXT=$(uv run cz bump --yes --get-next)" >> $GITHUB_ENV
            uv run cz bump --yes --dry-run | tee $CHANGE_LOG_DRY_RUN
          else
            echo GET_NEXT=$(uv run cz bump --yes --get-next --increment "$INC")
            uv run cz bump --yes --increment "$INC" --dry-run | tee $CHANGE_LOG_DRY_RUN
          fi

      - name: Check git tag collision
        run: |
          GET_TAG="release/${{ inputs.package }}/${{ env.GET_NEXT }}"
          
          if git --no-pager tag --list | grep -Fxq "$GET_TAG"; then
            echo "Git tag collision detected!"
            exit 1
          fi

      - name: Upload changelog artifact
        if: ${{ inputs.dry-run == true }}
        uses: actions/upload-artifact@v7
        with:
          name: changelog-dry-run-${{ inputs.package }}.md
          path: "apps/${{ inputs.package }}/changelog-dry-run.md"

  release:
    if: ${{ inputs.dry-run == false }}
    defaults:
      run:
        shell: bash
        working-directory: "apps/${{ inputs.package }}"
    runs-on: ubuntu-latest
    environment: release
    needs: validate-release
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.PROJECTX_CI_BOT_ID }}
          private-key: ${{ secrets.PROJECTX_CI_BOT_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Bump and Create Changelog
        run: |
          INC=${{ inputs.increment }}
          if [[ "$INC" == "AUTO" || -z "$INC" ]]; then
            echo "GET_NEXT=$(uv run cz bump --yes --get-next)" >> $GITHUB_ENV
            uv run cz bump --yes | tee changelog.md
            echo "DETECT_INCREMENT=$(grep -Eo 'MAJOR|MINOR|PATCH' changelog.md)" >> $GITHUB_ENV
          else
            uv run cz bump --yes --increment "$INC" --dry-run | tee $CHANGE_LOG_DRY_RUN
            echo "DETECT_INCREMENT=$INC" >> $GITHUB_ENV
            uv run cz bump --yes --increment "$INC"
          fi

      - name: Push commits with tags
        run: |
          git push && git push --tags
          
      - name: Ensure release branch exists (minor/major only)
        if: ${{ env.DETECT_INCREMENT != 'PATCH' }}
        run: |
            RELEASE_BRANCH="release/${{ inputs.package }}/${{ env.GET_NEXT }}"
            echo "create release branch $RELEASE_BRANCH"
            git branch $RELEASE_BRANCH
            git push $RELEASE_BRANCH

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          TAG="release/${{ inputs.package }}/$(uv run cz version --project)"

          awk "
            BEGIN { found=0 }
            \$0 ~ \"^## ${TAG}\" { found=1; next }
            found && \$0 ~ \"^## \" { exit }
            found { print }
          " CHANGELOG.md > release.md

          gh release create "$TAG" \
            --title "$TAG" \
            --notes-file release.md
