name: Create Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run - Create Changelog to stdout'
        required: false
        type: boolean
      package:
        description: 'Which slug to release'
        type: choice
        options:
          - orchestrator
        default: orchestrator
  push:
    branches:
      - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create the release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set git identity
        run: |
            git config --global user.email "tomas.miklusicak@cloudops.sk"
            git config --global user.name "tmiklu"
            git config --global push.followTags true


      - name: Dry run changelog
        if: ${{ inputs.dry-run == true }}
        run: |
          uv run cz bump --dry-run
        
      - name: Bump and Create Changelog
        if: ${{ inputs.dry-run == false }}
        run: |
          uv run cz bump --yes

      - name: Push commits with tags
        run: | 
          git push --follow-tags
          git fetch --tags

      - name: Create GitHub Release
        if: ${{ inputs.dry-run == false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          TAG=$(uv run cz version --project)
          grep "^## $TAG" CHANGELOG.md > release.md                                    
          awk "/## $TAG/{flag=1;next}/## [0-9]+/{flag=0}flag" CHANGELOG.md >> release.md
          gh release create "$TAG" \
            --title "$TAG" \
            --notes-file release.md
